### ISSUE TITLE
Sublime hangs when multiple lines of Scala code selected or commented

### ISSUE THREAD

**Issue by jamesthompson** [sublimescala/sublime-ensime#48] opened 2012-08-20 23:01 UTC
I get periodic hangs of Sublime when I select large (~ > 5  lines) of Scala code.

I also get hangs when I try to comment large sections of code and try to copy it. 

Does anyone else get this?

**Comment by rorygraves** [comment] 2015-07-08 20:43
Closing as can't reproduce

**Closed by rorygraves** 2015-07-08 20:43 UTC
Labels: critical
